[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
nnoremap <silent> fls :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
nnoremap <silent> fmr :<C-u>Unite file_mru buffer<CR>
nnoremap <silent> fbu :<C-u>Unite buffer<CR>
'''
# dot fileをfileに表示する
hook_post_source = 'call unite#custom#source("file", "matchers", "matcher_default")'
